import type { MotionPreset, ThemeTokens } from '../data/types'

export const theme: ThemeTokens = {
  colors: {
    text: '#475569',
    background: '#ffffff',
    backgroundSoft: '#f2fbf5',
    backgroundCool: '#edfdf7',
    surface: '#ffffff',
    surfaceStrong: '#fbfff8',
    muted: '#64748b',
    heading: '#12312b',
    line: '#d8eee1',
    accent: '#16a34a',
    accentStrong: '#22c55e',
    accentDark: '#047857',
    blue: '#0ea5e9',
    green: '#2fbf71',
    rose: '#f59e0b',
    headerBorder: 'rgba(22, 163, 74, 0.14)',
    headerBackground: 'rgba(255, 255, 255, 0.96)',
    topStripText: '#064e3b',
    topStripBackground: '#ecfdf5',
    brandMarkBackground: '#dcfce7',
    brandMarkBorder: '#bbf7d0',
    white: '#ffffff',
    navText: '#233b36',
    menuHoverBackground: '#ecfdf5',
    panelBorder: '#d8eee1',
    panelBackground: '#ffffff',
    menuItemBorder: '#bbf7d0',
    menuItemBackground: '#f5fff8',
    iconButtonBorder: '#d8eee1',
    ghostBorder: '#86efac',
    heroGradientStart: '#f0fdf4',
    heroGradientEnd: '#ffffff',
    pillBorder: '#bbf7d0',
    visualBorder: '#c8ead3',
    visualBarBackground: '#f5fff8',
    visualDotOrange: '#facc15',
    visualDotGreen: '#4ade80',
    visualDotBlue: '#38bdf8',
    visualSideBorder: '#dcfce7',
    visualSidebarText: '#64748b',
    visualActiveBackground: '#dcfce7',
    chartBackground: '#edfdf7',
    chartBorder: '#d7f2dd',
    visualCardBorder: '#bbf7d0',
    logoText: '#475569',
    ratingText: '#047857',
    ratingBackground: '#ecfdf5',
    ctaBackground: '#047857',
    ctaPillText: '#ecfdf5',
    ctaPillBorder: 'rgba(255, 255, 255, 0.28)',
    ctaPillBackground: 'rgba(255, 255, 255, 0.12)',
    error: '#b42318',
    noticeText: '#065f46',
    inputBorder: '#c8ead3',
    footerDivider: '#e5f4e8',
    whatsapp: '#26b55f',
  },
  shadows: {
    sm: '0 8px 24px rgba(6, 95, 70, 0.08)',
    md: '0 18px 54px rgba(6, 95, 70, 0.13)',
    button: '0 12px 26px rgba(22, 163, 74, 0.24)',
  },
  radii: {
    sm: '7px',
    md: '8px',
    pill: '999px',
  },
  gradients: {
    hero: 'linear-gradient(180deg, var(--color-hero-gradient-start) 0%, #f8fff9 46%, var(--color-hero-gradient-end) 82%)',
  },
  font: {
    sans:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
}

export const motionPreset: MotionPreset = {
  duration: 0.45,
  ease: [0.22, 1, 0.36, 1],
  distance: 22,
  stagger: 0.08,
}

export function toCssVarName(key: string, prefix: string) {
  return `--${prefix}-${key.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`)}`
}
